site_name: "Areal V2 Documentation"

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.annotate

  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets

plugins:
  - search
  - mermaid2

nav:
  - Home: [index.md]
  - Accounts: [accounts/auth.md, accounts/profiles.md]
  - Processing:
      [
        processing/index.md,
        processing/status.md,
        processing/classification.md,
        processing/extraction.md,
      ]
  - Gateways: gateways/index.md
  - CDBalancer: cdbalancer/index.md
  - Copilot: copilot/index.md
