site_name: "Areal V2 Documentation"
site_url: "https://docs.v2.areal.ai"

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.annotate

  logo: assets/logo.png
  favicon: assets/logo.png

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search

nav:
  - Home: [index.md]
  - Accounts: [auth.md]
  - Processing:
      [
        processing/processing.md,
        processing/status.md,
        processing/webhooks.md,
        processing/email.md,
      ]
  - Session: [sessions.md, loan_info.md]
  - CDBalancer: [cdbalancer.md]
  - Migration Guide: [migration/index.md, migration/examples.md]
