[project]
name = "areal-v2-docs"
version = "1.0.0"
authors = [{ name = "Yagiz Kilicarslan", email = "yagiz.kilicarslan@areal.ai" }]
description = "Areal V2 Documentation"
readme = "README.md"
requires-python = "~=3.13.1"
license = { file = "LICENSE" }
classifiers = ["License :: OSI Approved :: MIT License"]

dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.14",
    "mkdocs-mermaid2-plugin>=1.2.1",
]

[project.urls]
Homepage = "https://github.com/Arealai/areal-v2-docs"
